=== svzdvd/jdiff/test/comments.xsd
<?xml version="1.0" encoding="UTF-8"?>
<schema xmlns:xsd="http://www.w3.org/2000/10/XMLSchema">

<annotation>
  <documentation>
  Schema for JDiff comments.
  </documentation>
</annotation>

<xsd:element name="comments" type="commentsType">
<xsd:complexType name="commentType">
  <xsd:attribute name="name" type="xsd:string"/>
  <xsd:attribute name="jdversion" type="xsd:string"/>
  <xsd:sequence>
    <xsd:element name="comment" type="commentType" minOccurs='0' maxOccurs='unbounded'/>
  </xsd:sequence>
</xsd:complexType>

<xsd:complexType name="commentType">
  <xsd:sequence>
    <xsd:element name="identifier" type="identifierType" minOccurs='1' maxOccurs='unbounded'/>
    <xsd:element name="text" type="xsd:string" minOccurs='1' maxOccurs='1'/>
  </xsd:sequence>
</xsd:complexType>

<xsd:complexType name="identifierType">
  <xsd:attribute name="id" type="xsd:string"/>
</xsd:complexType>

</xsd:element>

</schema>

=== svzdvd/jdiff/examples/sample_output/newdocs/user_comments_for_SuperProduct_1.0_to_SuperProduct_2.0.xml
<?xml version="1.0" encoding="iso-8859-1" standalone="no"?>
<comments
  xmlns:xsi='http://www.w3.org/2000/10/XMLSchema-instance'
  xsi:noNamespaceSchemaLocation='comments.xsd'
  name="SuperProduct_1.0_to_SuperProduct_2.0"
  jdversion="1.0.5">

<!-- This file contains comments for a JDiff report. -->
<!-- It is used only in generating the report, and does not need to ship with the final report. -->

<!-- The id attribute in an identifier element identifiers the change as noted in the report. -->
<!-- An id has the form package[.class[.[ctor|method|field].signature]], where [] indicates optional text. -->
<!-- A comment element can have multiple identifier elements, which will -->
<!-- will cause the same text to appear at each place in the report, but -->
<!-- will be converted to separate comments when the comments file is used. -->
<!-- HTML tags in the text field will appear in the report. -->
<comment>
  <identifier id="com.acme.sp"/>
  <text>
    InsertCommentsHere
  </text>
</comment>
<comment>
  <identifier id="com.acme.sp.Locator"/>
  <text>
    InsertCommentsHere
  </text>
</comment>
<comment>
  <identifier id="com.acme.sp.SPImpl"/>
  <text>
    InsertCommentsHere
  </text>
</comment>
<comment>
  <identifier id="com.acme.sp.SPImpl.buildLog_changed(java.lang.String, int, boolean, int)"/>
  <text>
    InsertCommentsHere
  </text>
</comment>
<comment>
  <identifier id="com.acme.sp.SPImpl.createTable_removed(com.acme.sp.SP)"/>
  <text>
    InsertCommentsHere
  </text>
</comment>
<comment>
  <identifier id="com.acme.sp.SPImpl.flushTable_added(com.acme.sp.SP)"/>
  <text>
    InsertCommentsHere
  </text>
</comment>
<comment>
  <identifier id="com.acme.sp.SPImpl.saveName_changed(java.lang.String, int)"/>
  <text>
    InsertCommentsHere
  </text>
</comment>
<comment>
  <identifier id="com.acme.spextra"/>
  <text>
    InsertCommentsHere
  </text>
</comment>
<comment>
  <identifier id="com.acme.util"/>
  <text>
    InsertCommentsHere
  </text>
</comment>

</comments>
