=== svzdvd/jdiff/src/api.xsd
<?xml version="1.0" encoding="iso-8859-1" standalone="yes"?>
<schema xmlns:xsd="http://www.w3.org/2000/10/XMLSchema">

<annotation>
  <documentation>
  Schema for JDiff API representation.
  </documentation>
</annotation>

<xsd:element name="api" type="apiType">
<xsd:complexType name="apiType">
  <xsd:attribute name="name" type="xsd:string"/>
  <xsd:attribute name="jdversion" type="xsd:string"/>
  <xsd:sequence>
    <xsd:element name="package" type="packageType" minOccurs='1' maxOccurs='unbounded'/>
  </xsd:sequence>
</xsd:complexType>

<xsd:complexType name="packageType">
  <xsd:attribute name="name" type="xsd:string"/>
  <xsd:sequence>
    <xsd:element name="class" type="classType" minOccurs='1' maxOccurs='unbounded'/>
    <xsd:element name="doc" type="CDATA" minOccurs='0' maxOccurs='1'/>
  </xsd:sequence>
</xsd:complexType>

<xsd:complexType name="classType">
  <xsd:attribute name="name" type="xsd:string"/>
  <xsd:attribute name="extends" type="xsd:string" use='optional'/>
  <xsd:attribute name="abstract" type="xsd:boolean"/>
  <xsd:attribute name="static" type="xsd:boolean"/>
  <xsd:attribute name="final" type="xsd:boolean"/>
  <xsd:attribute name="deprecated" type="xsd:string"/>
  <xsd:attribute name="visibility" type="xsd:string"/>
  <xsd:sequence>
    <xsd:element name="implements" type="interfaceType" minOccurs='0' maxOccurs='unbounded'/>
    <xsd:element name="constructor" type="constructorType" minOccurs='1' maxOccurs='unbounded'/>
    <xsd:element name="method" type="methodType" minOccurs='0' maxOccurs='unbounded'/>
    <xsd:element name="field" type="fieldType" minOccurs='0' maxOccurs='unbounded'/>
    <xsd:element name="doc" type="CDATA" minOccurs='0' maxOccurs='1'/>
  </xsd:sequence>
</xsd:complexType>

<xsd:complexType name="interfaceType">
  <xsd:attribute name="name" type="xsd:string"/>
</xsd:complexType>

<xsd:complexType name="constructorType">
  <xsd:attribute name="name" type="xsd:string"/>
  <xsd:attribute name="type" type="xsd:string" use='optional'/>
  <xsd:attribute name="static" type="xsd:boolean"/>
  <xsd:attribute name="final" type="xsd:boolean"/>
  <xsd:attribute name="deprecated" type="xsd:string"/>
  <xsd:attribute name="visibility" type="xsd:string"/>
  <xsd:sequence>
    <xsd:element name="exception" type="exceptionType" minOccurs='0' maxOccurs='unbounded'/>
    <xsd:element name="doc" type="CDATA" minOccurs='0' maxOccurs='1'/>
  </xsd:sequence>
</xsd:complexType>

<xsd:complexType name="paramsType">
  <xsd:attribute name="name" type="xsd:string"/>
  <xsd:attribute name="type" type="xsd:string"/>
</xsd:complexType>

<xsd:complexType name="exceptionType">
  <xsd:attribute name="name" type="xsd:string"/>
</xsd:complexType>

<xsd:complexType name="methodType">
  <xsd:attribute name="name" type="xsd:string"/>
  <xsd:attribute name="return" type="xsd:string" use='optional'/>
  <xsd:attribute name="abstract" type="xsd:boolean"/>
  <xsd:attribute name="native" type="xsd:boolean"/>
  <xsd:attribute name="synchronized" type="xsd:boolean"/>
  <xsd:attribute name="static" type="xsd:boolean"/>
  <xsd:attribute name="final" type="xsd:boolean"/>
  <xsd:attribute name="deprecated" type="xsd:string"/>
  <xsd:attribute name="visibility" type="xsd:string"/>
  <xsd:sequence>
    <xsd:element name="exception" type="exceptionType" minOccurs='0' maxOccurs='unbounded'/>
    <xsd:element name="params" type="paramsType" minOccurs='0' maxOccurs='unbounded'/>
    <xsd:element name="doc" type="CDATA" minOccurs='0' maxOccurs='1'/>
  </xsd:sequence>
</xsd:complexType>

<xsd:complexType name="fieldType">
  <xsd:attribute name="name" type="xsd:string"/>
  <xsd:attribute name="type" type="xsd:string"/>
  <xsd:attribute name="transient" type="xsd:boolean"/>
  <xsd:attribute name="volatile" type="xsd:boolean"/>
  <xsd:attribute name="static" type="xsd:boolean"/>
  <xsd:attribute name="final" type="xsd:boolean"/>
  <xsd:attribute name="deprecated" type="xsd:string"/>
  <xsd:attribute name="visibility" type="xsd:string"/>
  <xsd:sequence>
    <xsd:element name="doc" type="CDATA" minOccurs='0' maxOccurs='1'/>
  </xsd:sequence>
</xsd:complexType>

</xsd:element>

</schema>

=== svzdvd/jdiff/build/output/SuperProduct2.0.xml
<?xml version="1.0"?>
<!-- Generated by the JDiff JavaDoc doclet -->
<!-- (http://www.pobox.com/~doar/src/jdiff) -->
<!-- on Thu Oct 11 09:21:41 PDT 2001 -->

<!-- XML Schema is used, but XHTML transitional DTD is needed for nbsp -->
<!-- entity definitions etc.-->
<!DOCTYPE api
     PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN"
     "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<api
  xmlns:xsi='http://www.w3.org/2000/10/XMLSchema-instance'
  xsi:noNamespaceSchemaLocation='api.xsd'
  name="SuperProduct2.0"
  jdversion="1.0">

<!--  Command line arguments =  -apiname SuperProduct2.0 -excludeclass private -excludemember private -->
<package name="ChangedPackage">
  <!-- start class ChangedPackage.AddedClass -->
  <class name="AddedClass" extends="java.lang.Object"
    abstract="false"
    static="false" final="false" visibility="public"
    deprecated="not deprecated">
    <constructor name="AddedClass"
      static="false" final="false" visibility="public"
      deprecated="not deprecated">
    </constructor>
  </class>
  <!-- end class ChangedPackage.AddedClass -->
  <!-- start class ChangedPackage.ChangedClass -->
  <class name="ChangedClass" extends="java.lang.Object"
    abstract="false"
    static="false" final="false" visibility="public"
    deprecated="not deprecated">
    <constructor name="ChangedClass" type="java.lang.String"
      static="false" final="false" visibility="public"
      deprecated="not deprecated">
    </constructor>
    <constructor name="ChangedClass" type="int, java.lang.String"
      static="false" final="false" visibility="public"
      deprecated="not deprecated">
    </constructor>
    <constructor name="ChangedClass"
      static="false" final="false" visibility="public"
      deprecated="not deprecated">
    </constructor>
    <method name="UnchangedMethod"
      abstract="false" native="false" synchronized="false"
      static="false" final="false" visibility="public"
      deprecated="not deprecated">
    </method>
    <method name="AddedMethod"
      abstract="false" native="false" synchronized="false"
      static="false" final="false" visibility="public"
      deprecated="not deprecated">
    </method>
    <method name="ChangedMethod" return="int"
      abstract="false" native="false" synchronized="false"
      static="false" final="false" visibility="public"
      deprecated="not deprecated">
      <param name="s1" type="java.lang.String"/>
      <param name="s2" type="java.lang.String"/>
      <param name="ac" type="ChangedPackage.AddedClass"/>
    </method>
    <field name="unchanged" type="boolean"
      transient="false" volatile="false"
      static="false" final="false" visibility="public"
      deprecated="not deprecated">
    </field>
    <field name="added" type="boolean"
      transient="false" volatile="false"
      static="false" final="false" visibility="public"
      deprecated="not deprecated">
    </field>
    <field name="changed" type="java.lang.String"
      transient="false" volatile="false"
      static="false" final="false" visibility="public"
      deprecated="not deprecated">
    </field>
  </class>
  <!-- end class ChangedPackage.ChangedClass -->
  <!-- start class ChangedPackage.ChangedClassImplements -->
  <class name="ChangedClassImplements" extends="java.lang.Object"
    abstract="false"
    static="false" final="false" visibility="public"
    deprecated="not deprecated">
    <implements name="java.lang.Comparable">
    </implements>
    <constructor name="ChangedClassImplements"
      static="false" final="false" visibility="package"
      deprecated="not deprecated">
    </constructor>
    <method name="compareTo" return="int"
      abstract="false" native="false" synchronized="false"
      static="false" final="false" visibility="public"
      deprecated="not deprecated">
      <param name="o" type="java.lang.Object"/>
    </method>
  </class>
  <!-- end class ChangedPackage.ChangedClassImplements -->
  <!-- start class ChangedPackage.ChangedClassImplements2 -->
  <class name="ChangedClassImplements2" extends="java.lang.Object"
    abstract="false"
    static="false" final="false" visibility="public"
    deprecated="not deprecated">
    <constructor name="ChangedClassImplements2"
      static="false" final="false" visibility="package"
      deprecated="not deprecated">
    </constructor>
  </class>
  <!-- end class ChangedPackage.ChangedClassImplements2 -->
  <!-- start class ChangedPackage.ChangedClassInherit -->
  <class name="ChangedClassInherit" extends="java.util.Hashtable"
    abstract="false"
    static="false" final="false" visibility="public"
    deprecated="not deprecated">
    <constructor name="ChangedClassInherit"
      static="false" final="false" visibility="public"
      deprecated="not deprecated">
    </constructor>
  </class>
  <!-- end class ChangedPackage.ChangedClassInherit -->
  <!-- start class ChangedPackage.ChangedClassInherit1 -->
  <class name="ChangedClassInherit1" extends="java.lang.Object"
    abstract="false"
    static="false" final="false" visibility="public"
    deprecated="not deprecated">
    <constructor name="ChangedClassInherit1"
      static="false" final="false" visibility="public"
      deprecated="not deprecated">
    </constructor>
  </class>
  <!-- end class ChangedPackage.ChangedClassInherit1 -->
  <!-- start class ChangedPackage.ChangedClassInner -->
  <class name="ChangedClassInner" extends="java.lang.Object"
    abstract="false"
    static="false" final="false" visibility="public"
    deprecated="not deprecated">
    <constructor name="ChangedClassInner"
      static="false" final="false" visibility="public"
      deprecated="not deprecated">
    </constructor>
  </class>
  <!-- end class ChangedPackage.ChangedClassInner -->
  <!-- start class ChangedPackage.ChangedClassInner$AddedInner -->
  <class name="ChangedClassInner$AddedInner" extends="java.lang.Object"
    abstract="false"
    static="false" final="false" visibility="public"
    deprecated="not deprecated">
    <constructor name="ChangedClassInner$AddedInner" type="ChangedPackage.ChangedClassInner"
      static="false" final="false" visibility="package"
      deprecated="not deprecated">
    </constructor>
    <field name="this$0" type="ChangedPackage.ChangedClassInner"
      transient="false" volatile="false"
      static="false" final="true" visibility="private"
      deprecated="not deprecated">
    </field>
  </class>
  <!-- end class ChangedPackage.ChangedClassInner$AddedInner -->
  <!-- start class ChangedPackage.ChangedClassInner$ChangedInner -->
  <class name="ChangedClassInner$ChangedInner" extends="java.lang.Object"
    abstract="false"
    static="false" final="false" visibility="public"
    deprecated="not deprecated">
    <constructor name="ChangedClassInner$ChangedInner" type="ChangedPackage.ChangedClassInner"
      static="false" final="false" visibility="package"
      deprecated="not deprecated">
    </constructor>
    <method name="AddedMethod"
      abstract="false" native="false" synchronized="false"
      static="false" final="false" visibility="package"
      deprecated="not deprecated">
    </method>
    <method name="ChangedMethod"
      abstract="false" native="false" synchronized="false"
      static="false" final="false" visibility="package"
      deprecated="not deprecated">
      <param name="i" type="int"/>
    </method>
    <field name="this$0" type="ChangedPackage.ChangedClassInner"
      transient="false" volatile="false"
      static="false" final="true" visibility="private"
      deprecated="not deprecated">
    </field>
  </class>
  <!-- end class ChangedPackage.ChangedClassInner$ChangedInner -->
  <!-- start class ChangedPackage.ChangedClassLevelModifiers -->
  <class name="ChangedClassLevelModifiers" extends="java.lang.Object"
    abstract="false"
    static="false" final="false" visibility="public"
    deprecated="not deprecated">
    <constructor name="ChangedClassLevelModifiers"
      static="false" final="false" visibility="public"
      deprecated="not deprecated">
    </constructor>
  </class>
  <!-- end class ChangedPackage.ChangedClassLevelModifiers -->
  <!-- start class ChangedPackage.ChangedClassLevelModifiers1 -->
  <class name="ChangedClassLevelModifiers1" extends="java.lang.Object"
    abstract="false"
    static="false" final="false" visibility="public"
    deprecated="not deprecated">
    <constructor name="ChangedClassLevelModifiers1"
      static="false" final="false" visibility="package"
      deprecated="not deprecated">
    </constructor>
  </class>
  <!-- end class ChangedPackage.ChangedClassLevelModifiers1 -->
  <!-- start class ChangedPackage.ChangedClassLevelModifiers3 -->
  <class name="ChangedClassLevelModifiers3" extends="java.lang.Object"
    abstract="false"
    static="false" final="false" visibility="public"
    deprecated="not deprecated">
    <constructor name="ChangedClassLevelModifiers3"
      static="false" final="false" visibility="package"
      deprecated="not deprecated">
    </constructor>
  </class>
  <!-- end class ChangedPackage.ChangedClassLevelModifiers3 -->
  <!-- start class ChangedPackage.ChangedClassLevelModifiers4 -->
  <class name="ChangedClassLevelModifiers4" extends="java.lang.Object"
    abstract="true"
    static="false" final="false" visibility="public"
    deprecated="not deprecated">
    <constructor name="ChangedClassLevelModifiers4"
      static="false" final="false" visibility="package"
      deprecated="not deprecated">
    </constructor>
  </class>
  <!-- end class ChangedPackage.ChangedClassLevelModifiers4 -->
  <!-- start class ChangedPackage.ChangedClassLevelModifiers5 -->
  <class name="ChangedClassLevelModifiers5" extends="java.lang.Object"
    abstract="false"
    static="false" final="false" visibility="public"
    deprecated="not deprecated">
    <constructor name="ChangedClassLevelModifiers5"
      static="false" final="false" visibility="package"
      deprecated="not deprecated">
    </constructor>
