=== svzdvd/jdiff/src/config.xsd
<?xml version="1.0" encoding="iso-8859-1" standalone="no"?>
<xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema">

<xsd:annotation>
  <xsd:documentation>
  Schema for JDiff configuration file.
  </xsd:documentation>
</xsd:annotation>

<xsd:element name="config" type="configType"/>

<xsd:complexType name="configType">
  <xsd:sequence>
    <xsd:element name="api" type="apiType" minOccurs='1' maxOccurs='2'/>
<!-- Should be 1 if there are two APIs -->        
    <xsd:element name="report" type="reportType" minOccurs='0' maxOccurs='unbounded'/>
  </xsd:sequence>
  <xsd:attribute name="name" type="xsd:string"/>
  <xsd:attribute name="jdversion" type="xsd:string"/>
</xsd:complexType>

<xsd:complexType name="apiType">
  <xsd:sequence>
    <xsd:element name="javadoc" type="javadocType" minOccurs='1' maxOccurs='1'/>
    <xsd:element name="source" type="sourceType" minOccurs='1' maxOccurs='1'/>
    <xsd:element name="jdiff" type="jdiffType" minOccurs='0' maxOccurs='1'/>
  </xsd:sequence>
</xsd:complexType>

<xsd:complexType name="javadocType">
  <xsd:attribute name="args" type="xsd:string"/>
  <xsd:attribute name="packages" type="xsd:string"/>
</xsd:complexType>

<xsd:complexType name="sourceType">
  <xsd:attribute name="location" type="xsd:string"/>
  <xsd:attribute name="packages" type="xsd:string"/>
</xsd:complexType>

<xsd:complexType name="jdiffType">
  <xsd:attribute name="baseURI" type="xsd:string"/>
</xsd:complexType>

<xsd:complexType name="reportType">
  <xsd:attribute name="output" type="xsd:string"/>
  <xsd:attribute name="args" type="xsd:string"/>
  <xsd:attribute name="javadocold" type="xsd:string"/>
  <xsd:attribute name="javadocnew" type="xsd:string"/>
  <xsd:attribute name="stats" type="xsd:boolean"/>
  <xsd:attribute name="nodocchanges" type="xsd:boolean"/>
</xsd:complexType>

</xsd:schema>

=== svzdvd/jdiff/examples/example.xml
<?xml version="1.0" encoding="iso-8859-1" standalone="no"?>
<config
  xmlns:xsi='http://www.w3.org/2001/XMLSchema-instance'
  xsi:noNamespaceSchemaLocation='config.xsd'
  name="Example Configuration"
  jdversion="1.0.6">

<!-- This file contains a configuration for running Javadoc. and -->
<!-- optionally for running JDiff to compare two APIs. -->

<!-- If there is only one API element, Javadoc is produced for it, -->
<!-- using the arguments in javadoc element. -->
<!-- TODO use the line continuation char in javadoc? -->
<api name="Old Test API">
  <javadoc args="-private -doctitle \"JDiff Test Old API\"
  -windowtitle \"JDiff Test Old API\""/>
  <!-- Can have multiple source elements -->
  <source location="old" packages=
    "RemovedPackage ChangedPackage ChangedPackageDoc ChangedPackageDoc2"/>
</api>

<!-- If there are two API elements in a config file, JDiff reports the -->
<!-- changes between the first and second API. Javadoc output is also -->
<!-- produced for each API if javadoc is specified. -->
<api name="New Test API">
  <javadoc args="-private -doctitle \"JDiff Test New API\" -windowtitle \"JDiff Test New API\""/>
  <!-- Can have multiple source elements -->
  <source location="new" packages=
    "AddedPackage ChangedPackage ChangedPackageDoc ChangedPackageDoc2"/>
  <!-- Arguments for jdiff are passed in the jdiff element -->
  <jdiff baseURI="file:///C:/jdiff/lib"/>
</api>

<!-- Configuration of each JDiff report using the same two APIs. -->
<report output="newdocs"
       args="-private -excludeclass private -excludemember private" 
       javadocold="../../olddocs/" javadocnew="../../newdocs/" stats="true"/>
<report output="newdocs2"
       args="-private -excludeclass private -excludemember private" 
       javadocold="../../olddocs/" javadocnew="../../newdocs/"
       stats="true" nodocchanges="true"/>
</config>
